name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: chktex main.tex > lint_report.txt
        continue-on-error: True

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lint_report.txt
          path: lint_report.txt


  build-manuscript:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - uses: actions/checkout@v4

      - name: Create out dir
        run: mkdir out

      - name: Build manuscript
        run: latexmk main_manuscript.tex > out/build_report_manuscript.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: manuscript
          path: out/

  build-booklet:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - uses: actions/checkout@v4

      - name: Create out dir
        run: mkdir out

      - name: Build booklet
        run: latexmk main_booklet.tex > out/build_report_booklet.txt

      - name: Prepend cover
        run: gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None -sOutputFile=out/main_booklet_with_cover.pdf  cover.pdf out/main_booklet.pdf

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: booklet
          path: out
